# Generated by Django 4.1.2 on 2023-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDecided',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('missed', models.BooleanField()),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='Decided',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('validator_public_key', models.CharField(db_index=True, max_length=100)),
                ('height', models.IntegerField(db_index=True)),
                ('signers', models.CharField(max_length=80)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'unique_together': {('validator_public_key', 'height')},
            },
        ),
    ]
