# Generated by Django 4.1.2 on 2023-04-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decided',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
