# Generated by Django 4.1.2 on 2023-04-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0003_alter_decided_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decided',
            name='validator_public_key',
            field=models.CharField(db_index=True, max_length=110),
        ),
    ]
