# Generated by Django 4.1.2 on 2023-04-10 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0004_alter_decided_validator_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='operatordecided',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatordecided',
            name='operator_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatordecided',
            name='time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operatordecided',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operatordecided',
            name='missed',
            field=models.BooleanField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='operatordecided',
            unique_together={('operator_id', 'height')},
        ),
        migrations.RemoveField(
            model_name='operatordecided',
            name='create_time',
        ),
    ]
