# Generated by Django 4.1.2 on 2023-04-10 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0005_tag_operatordecided_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatordecided',
            name='decided_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
