# Generated by Django 4.1.2 on 2023-04-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0006_operatordecided_decided_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operatordecided',
            unique_together=set(),
        ),
    ]
