# Generated by Django 4.1.2 on 2023-04-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0007_alter_operatordecided_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('public_key', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('ssv_balance_human', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField()),
                ('performance', models.FloatField()),
                ('timestamp', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='operatordecided',
            name='decided_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='OperatorValidator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField()),
                ('validator_public_key', models.CharField(max_length=110)),
            ],
            options={
                'unique_together': {('operator_id', 'validator_public_key')},
            },
        ),
    ]
