# Generated by Django 4.1.2 on 2023-04-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0008_account_performance_alter_operatordecided_decided_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=42, null=True)),
                ('active', models.BooleanField(default=False)),
                ('validator_count', models.IntegerField(default=0)),
                ('fee_human', models.FloatField(default=0)),
                ('performance_1day', models.FloatField(default=0)),
                ('performance_1month', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=110)),
                ('owner_address', models.CharField(max_length=42)),
                ('active', models.BooleanField(default=False)),
                ('performance_1day', models.FloatField(default=0)),
                ('performance_1month', models.FloatField(default=0)),
                ('operators', models.ManyToManyField(to='ssv.operator')),
            ],
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='public_key',
            new_name='address',
        ),
    ]
