# Generated by Django 4.1.2 on 2023-04-11 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0009_operator_validator_delete_performance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='owner_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='validator',
            name='public_key',
            field=models.CharField(max_length=110, unique=True),
        ),
    ]
