# Generated by Django 4.1.2 on 2023-04-13 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0010_alter_validator_owner_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='performance_1day',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='performance_1month',
        ),
        migrations.CreateModel(
            name='OperatorPerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssv.operator')),
            ],
        ),
    ]
