# Generated by Django 4.1.2 on 2023-04-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0013_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='est_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='operator',
            name='snapshot_index',
            field=models.BigIntegerField(default=0),
        ),
    ]
