# Generated by Django 4.1.2 on 2023-04-21 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssv', '0014_cluster_est_days_operator_snapshot_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='liquidated',
            field=models.BooleanField(default=False),
        ),
    ]
