# Generated by Django 4.1.2 on 2023-11-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssv", "0015_cluster_liquidated"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="last_sync_block_number",
            field=models.IntegerField(default=0),
        ),
    ]
