# Generated by Django 4.1.2 on 2023-11-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ssv", "0016_cluster_last_sync_block_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="cluster",
            name="balance",
            field=models.CharField(default="0", max_length=80),
        ),
        migrations.AddField(
            model_name="cluster",
            name="index",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="cluster",
            name="network_fee_index",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name="cluster",
            unique_together={("owner", "operator_ids")},
        ),
    ]
