# Generated by Django 4.1.2 on 2022-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0006_rule_create_time_rule_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='history_display',
            field=models.CharField(default='aaa', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='history_value_map',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='history_y_unit',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
