# Generated by Django 4.1.2 on 2023-04-09 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('public_key', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('ssv_balance_human', models.FloatField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_public_key', models.CharField(max_length=42)),
                ('status', models.CharField(max_length=10)),
                ('validator_count', models.IntegerField()),
                ('fee_human', models.FloatField()),
                ('performance_1day', models.FloatField()),
            ],
            options={
                'db_table': 'operator',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_id', models.IntegerField()),
                ('performance', models.FloatField()),
                ('timestamp', models.IntegerField()),
            ],
            options={
                'db_table': 'performance',
            },
        ),
    ]
