# Generated by Django 3.2.15 on 2022-10-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('public_key', models.CharField(max_length=42, primary_key=True, serialize=False)),
                ('ssv_balance_human', models.FloatField()),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('account_public_key', models.CharField(max_length=42)),
                ('status', models.CharField(max_length=10)),
                ('validator_count', models.IntegerField()),
                ('fee_human', models.FloatField()),
            ],
            options={
                'db_table': 'operator',
            },
        ),
    ]
