# Generated by Django 3.2.15 on 2022-10-18 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='raw_content',
        ),
    ]
