# Generated by Django 3.2.15 on 2022-10-20 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0002_remove_alert_raw_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
