# Generated by Django 4.1.2 on 2022-11-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0003_rule_disabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='query_attr',
            field=models.JSONField(default='{}'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='query_template',
            field=models.TextField(default='aa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rule',
            name='expr',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
