# Generated by Django 4.1.2 on 2022-11-25 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0004_metric_query_attr_metric_query_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='alert_template',
            field=models.TextField(default='aaa'),
            preserve_default=False,
        ),
    ]
