# Generated by Django 4.1.2 on 2022-11-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0007_metric_history_display_name_metric_history_value_map_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='history_value_map',
            field=models.JSONField(blank=True),
        ),
    ]
