# Generated by Django 3.2.15 on 2022-10-18 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0001_initial'),
        ('alerting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='prom.rule'),
            preserve_default=False,
        ),
    ]
