# Generated by Django 3.2.15 on 2022-10-18 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0002_remove_alert_raw_content'),
        ('alerting', '0002_subscribe_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='prom_alert_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alert',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prom.metric'),
        ),
        migrations.AlterField(
            model_name='alert',
            name='subscribe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerting.subscribe'),
        ),
    ]
