# Generated by Django 3.2.15 on 2022-10-20 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0003_rule_disabled'),
        ('alerting', '0003_auto_20221018_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='prom.rule'),
        ),
    ]
