# Generated by Django 3.2.15 on 2022-10-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerting', '0004_alter_subscribe_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='has_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together={('subscribe', 'prom_alert_id')},
        ),
    ]
