# Generated by Django 4.1.2 on 2022-11-29 05:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prom', '0008_alter_metric_history_value_map'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerting', '0006_alter_alert_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('user', 'rule'), ('name', 'user')},
        ),
    ]
